# Example file
plugins:
  - 'https://raw.githubusercontent.com/jakhu/retis-tester-1/master/psf.cson'
  #- 'https://github.com/Gum-Joe/TeddyAlive/archive/MasterBackup.zip'
name: 'retis-example'
local: true
nvm:
  - stable
language: nodejs
install: npm install
global:
  npm:
    - buildup
  gem:
  #  - Gemfile: ./Gemfile
    - sass
