# Example file
plugins:
  - 'https://github.com/jakhu/retis-tester-1/archive/master.zip'
  - 'https://github.com/Gum-Joe/TeddyAlive/archive/MasterBackup.zip'
name: 'retis-example'
local: true
nvm:
  - stable
language: nodejs
install: npm install
global:
  npm:
    - buildup
