---
plugins:
  - "https://raw.githubusercontent.com/jakhu/retis-tester-1/test/psf.cson"
name: "retis-example"
out_dir: "./build"
os: "Linux"
scm:
  type: "git"
  remote: "origin"
  user:
    name: Gum-Joe
local: true
nvm:
  - "stable"
language: "ruby"

# CMDs
pre_install: echo test
install:
  - 'npm install -g buildup --color=always'
  - 'echo More!'
post_install: 'echo post'
build: 'echo build cmd'

global:
  npm:
    - "buildup"
  gem:
    - "sass"
  pip:
    - "request"
sh:
  hide_env: false

env:
  - TEST=test
