gulp = require 'gulp'
coffee = require 'gulp-coffee'
gutil = require 'gulp-util'
watch = require 'gulp-watch'
batch = require 'gulp-batch'
fs = require 'fs'
mkdirp = require 'mkdirp'
clean = require 'gulp-clean'

src_dir = './src'
out_dir = './lib/'
compiler_prefix = '**/*.coffee'
full_src_dir = "#{src_dir}/#{compiler_prefix}"
dir_list = ['src', 'lib'];
bin_dir = './bin/'
# Register task 'clean'
gulp.task 'clean', ->
  gulp.src(out_dir, read: false)
    .pipe(clean());
  console.log ""
  gutil.log('Cleaned directories.');
  console.log ""

# Register task 'mkdir'
gulp.task 'mkdir', ['clean'], ->
  for dir in dir_list
    mkdirp(dir) if fs.existsSync(dir) == false
  console.log ""
  gutil.log('Created directories.');
  console.log ""

# Register task 'coffee'
gulp.task 'coffee', ['mkdir'] , ->
  gulp.src(full_src_dir)
    .pipe coffee(bare: true).on('error', (err) -> throw err)
    .pipe gulp.dest(out_dir)
  gulp.src("#{src_dir}/bin/*.coffee")
    .pipe coffee(bare: true).on('error', (err) -> throw err)
    .pipe gulp.dest(bin_dir)
  console.log ""
  gutil.log('Finished compiling coffee script.');
  gutil.log('From:', full_src_dir)
  gutil.log('To:', out_dir)
  console.log ""

# Watch task
gulp.task 'watch:coffee', ->
  gulp.watch full_src_dir, ['coffee']

# Default task
gulp.task 'default', ['coffee'], ->
  # Do nothing

# ---
# generated by js2coffee 2.2.0
