// Generated by CoffeeScript 1.10.0
(function() {
  var Logger, app, fs, parseConfig, path, plugins;

  Logger = require('./logger').Logger;

  fs = require('fs');

  path = require('path');

  parseConfig = require('./parser').parseConfig;

  plugins = require('./plugins');

  app = module.exports = {};


  /*
   * Build method
   * @param options {Object} Options
   */

  app.build = function(options) {
    var i, len, p, ref;
    this.logger = new Logger('retis', options);
    this.logger.info('Scanning for build specification...');
    this.logger.deb("CWD: " + ("\'" + (process.cwd()) + "\'").green);
    this.config = parseConfig(options);
    if (this.config.hasOwnProperty('name')) {
      this.name = this.config.name;
    }
    if (process.platform !== 'win32' && this.config.hasOwnProperty('name') === false) {
      this.name = process.cwd().split("/");
    }
    if (process.platform === 'win32' && this.config.hasOwnProperty('name') === false) {
      this.name = process.cwd().split("\\");
    }
    this.logger.deb("Received config from parser.");
    this.logger.deb("Starting build...");
    this.logger.info("");
    this.logger.info(":---------------------------------------------:");
    if (this.config.hasOwnProperty('name') === false) {
      this.logger.info("  Building Project \'" + this.name[this.name.length - 1] + "\'...");
    }
    if (this.config.hasOwnProperty('name') === true) {
      this.logger.info("  Building Project \'" + this.name + "\'...");
    }
    this.logger.info(":---------------------------------------------:");
    this.logger.info("");
    if (this.config.hasOwnProperty('plugins')) {
      this.logger.info('Downloading plugins...');
      this.logger.info('');
      ref = this.config.plugins;
      for (i = 0, len = ref.length; i < len; i++) {
        p = ref[i];
        plugins.fetchPlugin(p, options);
      }
    }
  };

}).call(this);
