// Generated by CoffeeScript 1.10.0
(function() {
  var Logger, app, logger;

  Logger = require('./logger').Logger;

  app = module.exports = {};

  logger = new Logger('retis');


  /*
   * Build method
   * @param options {Object} Options
   */

  app.build = function(options) {
    return console.log('Building');
  };

}).call(this);
