// Generated by CoffeeScript 1.10.0
var ENV, Logger, debug_module;

debug_module = require('debug');

require('colours');

ENV = process.env;


/*
 * Logger Class
 *
 * @class Logger
 * @param prefix {String} prefix
 */

Logger = (function() {
  function Logger(prefix, options) {
    this.prefix = prefix;
    this.debug = debug_module(prefix);
    this.options = options;
    this.starttime = Date.now();
    if (typeof this.options.silent !== 'undefined' && this.options.silent) {
      console.log = function() {};
    }
  }


  /*
   * Info method
   *
   * @colour green
   * @param txt {String} Text to output
   */

  Logger.prototype.info = function(txt) {
    var infostring;
    infostring = "INFO";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(("" + infostring).green + " " + txt);
    } else {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.log(("[" + this.prefix + " " + infostring + "]").green + " " + txt);
      }
    }
  };


  /*
   * Running method
   *
   * @colour magenta
   * @param txt {String} Text to output
   */

  Logger.prototype.running = function(txt) {
    var runningstring;
    runningstring = "EXEC";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(("" + runningstring).blue.bold + " " + txt);
    } else {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.log(("[" + this.prefix + " " + runningstring + "]").blue.bold + " " + txt);
      }
    }
  };


  /*
   * Stdout method
   *
   * @colour magenta
   * @param txt {String} Text to output
   */

  Logger.prototype.stdout = function(txt) {
    var runningstring;
    runningstring = "SOUT";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(("" + runningstring).magenta.bold + " " + txt);
    } else {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.log(("[" + this.prefix + " " + runningstring + "]").magenta.bold + " " + txt);
      }
    }
  };


  /*
   * Stderr method
   *
   * @colour red
   * @param txt {String} Text to output
   */

  Logger.prototype.stderr = function(txt) {
    var runningstring;
    runningstring = "SERR";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(("" + runningstring).red.bold + " " + txt);
    } else {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.error(("[" + this.prefix + " " + runningstring + "]").red.bold + " " + txt);
      }
    }
  };


  /*
   * Error method
   *
   * @colour red
   * @param txt {String} Text to output
   */

  Logger.prototype.err = function(txt) {
    var runningstring;
    runningstring = "ERROR!";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(("" + runningstring).red.bold + " " + txt);
    } else {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.error(("[" + this.prefix + " " + runningstring + "]").red.bold + " " + txt);
      }
    }
  };


  /*
   * Warn method
   *
   * @colour yellow
   * @param txt {String} Text to output
   */

  Logger.prototype.warn = function(txt) {
    var warnstring;
    warnstring = "WARN!";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(("" + warnstring).yellow + " " + txt);
    } else {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.warn(("[" + this.prefix + " " + warnstring + "]").yellow + " " + txt);
      }
    }
  };


  /*
   * Debug method
   *
   * @colour cyan
   * @param txt {String} Text to output
   */

  Logger.prototype.deb = function(txt) {
    var debugstring;
    debugstring = "DEBUG";
    if (typeof ENV['DEBUG'] !== 'undefined' && ~ENV['DEBUG'].indexOf(this.prefix)) {
      return this.debug(debugstring.cyan + " " + txt);
    } else if (this.options.hasOwnProperty('debug') && typeof this.options.debug !== 'undefined') {
      if (!this.options.hasOwnProperty('silent') || !this.options.silent) {
        return console.log(("[" + this.prefix + " " + debugstring + "]").cyan + " " + txt);
      }
    }
  };

  return Logger;

})();

module.exports = {
  Logger: Logger
};
