// Generated by CoffeeScript 1.10.0

/*
 * Module dependencies
 */
var fs, mkdirp, os, path;

mkdirp = require('mkdirp');

path = require('path');

fs = require('fs');

os = require('os');


/*
 * Mkdirs
 */

module.exports = function(logger) {

  /*
   * Vars
   * These have to be declared on run
   * of function
   * This so process.cwd() is correct.
   */
  var files, i, j, len, len1, list, m, results, retis_home, retis_loc, retis_plugin_dir;
  retis_loc = path.join(process.cwd(), '.retis');
  retis_home = path.join(os.homedir(), '.retis');
  retis_plugin_dir = retis_home + "/plugins";
  list = [retis_home, retis_plugin_dir, retis_plugin_dir + "/.tmp", retis_plugin_dir + "/.tmp/download", retis_plugin_dir + "/.tmp/extract", retis_plugin_dir + "/.config", retis_loc];
  files = [
    {
      name: retis_loc + "/config.cson",
      contents: "file: \"config.cson\""
    }
  ];
  logger.deb("Making directories if they do not exist...");
  for (i = 0, len = list.length; i < len; i++) {
    m = list[i];
    if (!fs.existsSync(m)) {
      logger.deb("Creating dir " + m + "...");
      mkdirp(m, function(err) {
        if (err) {
          throw err;
        }
      });
      logger.deb("Created dir " + m + ".");
    }
    if (m === list[list.length - 1]) {
      logger.deb("Done making directories.");
    }
  }
  logger.deb("Making files if they do not exist...");
  results = [];
  for (j = 0, len1 = files.length; j < len1; j++) {
    m = files[j];
    if (!fs.existsSync(m.name)) {
      logger.deb("Creating file " + m.name + "...");
      logger.deb("Adding contents to file " + m.name + "...");
      logger.deb("Contents: " + m.contents);
      fs.writeFileSync(m.name, m.contents);
      logger.deb("Created file " + m.name + ".");
    }
    if (m === files[files.length - 1]) {
      results.push(logger.deb("Done making file."));
    } else {
      results.push(void 0);
    }
  }
  return results;
};
