// Generated by CoffeeScript 1.10.0

/*
 * Module dependencies
 */
var os_mod, ose;

os_mod = require('os');


/*
 * Vars
 */

ose = module.exports = {};


/*
 * Validate OS
 * @param os {String} OS
 * @param logger {Logger} Logger
 */

ose.validateOS = function(os, logger) {
  if (os !== 'Linux' && os !== 'OSX' && os !== 'Windows') {
    logger.err("Invalid OS " + ("\'" + os + "\'").red.bold + "!");
    logger.err("Should be either " + "Linux" + ", " + "Windows" + " or " + "OSX" + ".");
    throw new Error("Invalid OS " + os + "! Should be either \'Linux\', \'OSX\' or \'Windows\'.");
  }
};
