// Generated by CoffeeScript 1.10.0

/*
 * Module dependencies
 */

(function() {
  var Logger, fs, https, mkdirp, os, path, plugins, request, retis_plugin_dir, unzip, urlm, zlib;

  Logger = require('./logger').Logger;

  fs = require('fs');

  path = require('path');

  os = require('os');

  mkdirp = require('mkdirp');

  request = require('request');

  https = require('follow-redirects').https;

  fs = require('fs');

  urlm = require('url');

  unzip = require('unzip2');

  zlib = require('zlib');


  /*
   * Vars
   */

  plugins = module.exports = {};

  retis_plugin_dir = '.retis/plugins';

  retis_plugin_dir = path.join(os.homedir(), retis_plugin_dir);


  /*
   * Download method
   * @param url {String} URL to download
   * @param options {Object} Options
   */

  plugins.fetchPlugin = function(url, options) {
    var file_save, file_stream, logger;
    logger = new Logger('retis', options);
    logger.deb('Downloading plugin...');
    logger.deb("Creating dir " + retis_plugin_dir + "...");
    if (fs.existsSync(retis_plugin_dir) === false) {
      mkdirp(retis_plugin_dir, function(err) {
        if (err) {
          throw err;
        }
      });
    }
    logger.deb("Created dir " + retis_plugin_dir + ".");
    logger.deb("Creating dir " + retis_plugin_dir + "/.tmp...");
    if (fs.existsSync(retis_plugin_dir + "/.tmp") === false) {
      mkdirp(retis_plugin_dir + "/.tmp", function(err) {
        if (err) {
          throw err;
        }
      });
    }
    logger.deb("Created dir " + retis_plugin_dir + "/.tmp.");
    logger.info("Downloading " + url + "...");
    this.download_options = {
      hostname: urlm.parse(url).hostname,
      path: urlm.parse(url).path,
      method: 'GET'
    };
    file_save = (retis_plugin_dir + "/.tmp/") + url.split('/')[url.split('/').length - 1];
    file_stream = fs.createWriteStream(file_save);
    this.req = https.request(this.download_options, function(res) {
      logger.deb('statusCode: ' + res.statusCode);
      logger.deb('headers: \n' + JSON.stringify(res.headers, null, '\t'));
      res.on('end', function() {
        logger.info("Downloaded " + url + ".");
        return console.log(zlib.unzipSync(fs.readFileSync(file_save)));
      });
      return res.on('data', function(d) {
        file_stream.write(d);
      });
    });
    this.req.end();
    this.req.on('error', function(e) {
      console.error(e);
    });
  };

}).call(this);
