// Generated by CoffeeScript 1.10.0

/*
 * Module dependencies
 */
var Logger, logger, which;

which = require('which');

require('colours');

Logger = require('./logger').Logger;

which = which.sync;


/*
 * Vars
 */

logger = new Logger('retis', {});


/*
 * Which function
 * @param cmd {String} Command to check
 */

module.exports = function(cmd) {
  var err, error;
  try {
    return which(cmd);
  } catch (error) {
    err = error;
    logger.warn("Command " + cmd.cyan.bold + " not found on system. Is it installed?");
    return cmd;
  }
};
